services:
    ngmore_installer.installer.ngmore:
        class: Netgen\Bundle\MoreInstallerBundle\Installer\NetgenMoreInstaller
        public: false
        calls:
            - [setInstallerDataPath, ["%kernel.project_dir%/vendor/netgen/more-site-data/ngmore"]]
            - [setStoragePath, [web/var/site/storage]]
        parent: ezplatform.installer.db_based_installer
        tags:
            - {name: ezplatform.installer, type: ngmore}

    ngmore_installer.installer.ngmore_clean:
        class: Netgen\Bundle\MoreInstallerBundle\Installer\NetgenMoreInstaller
        public: false
        calls:
            - [setInstallerDataPath, ["%kernel.project_dir%/vendor/netgen/more-site-data/ngmore-clean"]]
            - [setStoragePath, [web/var/site/storage]]
        parent: ezplatform.installer.db_based_installer
        tags:
            - {name: ezplatform.installer, type: ngmore-clean}
