parameters:
    ngmore_installer.installer.ngmore.class: Netgen\Bundle\MoreInstallerBundle\Installer\NetgenMoreInstaller

services:
    ngmore_installer.installer.ngmore:
        class: "%ngmore_installer.installer.ngmore.class%"
        calls:
            - [setInstallerDataPath, [%kernel.root_dir%/../vendor/netgen/more-site-data/ngmore]]
            - [setStoragePath, [web/var/site/storage]]
        parent: ezplatform.installer.db_based_installer
        tags:
            - {name: ezplatform.installer, type: ngmore}
