parameters:
    netgen_site_installer.remote_media.field_types_to_migrate:
        - ezimage
        - ezbinaryfile
        - ezmedia

    netgen_site_installer.remote_media.excluded_field_identifiers: []

services:
    netgen_site_installer.media_site:
        class: Netgen\Bundle\SiteInstallerBundle\Installer\NetgenSiteInstaller
        public: false
        calls:
            - [setInstallerDataPath, ["%kernel.project_dir%/vendor/netgen/media-site-data/netgen-media"]]
            - [setStoragePath, [web/var/site/storage]]
        parent: ezplatform.installer.db_based_installer
        tags:
            - {name: ezplatform.installer, type: netgen-media}

    netgen_site_installer.media_site_clean:
        class: Netgen\Bundle\SiteInstallerBundle\Installer\NetgenSiteInstaller
        public: false
        calls:
            - [setInstallerDataPath, ["%kernel.project_dir%/vendor/netgen/media-site-data/netgen-media-clean"]]
            - [setStoragePath, [web/var/site/storage]]
        parent: ezplatform.installer.db_based_installer
        tags:
            - {name: ezplatform.installer, type: netgen-media-clean}

    netgen_site_installer.media_site_remote_clean:
        class: Netgen\Bundle\SiteInstallerBundle\Installer\NetgenRemoteMediaSiteInstaller
        public: false
        calls:
            - [ setRepository, [ "@ezpublish.api.repository" ] ]
            - [ setFieldTypesToMigrate, [ "%netgen_site_installer.remote_media.field_types_to_migrate%" ] ]
            - [ setExcludedFieldIdentifiers, [ "%netgen_site_installer.remote_media.excluded_field_identifiers%" ] ]
        parent: netgen_site_installer.media_site_clean
        tags:
            - { name: ezplatform.installer, type: netgen-media-remote-clean }
