services:
    netgen_site_installer.media_site:
        class: Netgen\Bundle\SiteInstallerBundle\Installer\NetgenSiteInstaller
        calls:
            - [setInstallerDataPath, ["%kernel.project_dir%/vendor/netgen/media-site-data/netgen-media"]]
            - [setStoragePath, [public/var/site/storage]]
        parent: Ibexa\Bundle\RepositoryInstaller\Installer\DbBasedInstaller
        tags:
            - { name: ibexa.installer, type: netgen-media }
