services:
    netgen_site_installer.media_site:
        class: Netgen\Bundle\SiteInstallerBundle\Installer\NetgenSiteInstaller
        public: false
        calls:
            - [setInstallerDataPath, ["%kernel.project_dir%/vendor/netgen/media-site-data/netgen-media"]]
            - [setStoragePath, [web/var/site/storage]]
        parent: ezplatform.installer.db_based_installer
        tags:
            - {name: ezplatform.installer, type: netgen-media}

    netgen_site_installer.media_site_clean:
        class: Netgen\Bundle\SiteInstallerBundle\Installer\NetgenSiteInstaller
        public: false
        calls:
            - [setInstallerDataPath, ["%kernel.project_dir%/vendor/netgen/media-site-data/netgen-media-clean"]]
            - [setStoragePath, [web/var/site/storage]]
        parent: ezplatform.installer.db_based_installer
        tags:
            - {name: ezplatform.installer, type: netgen-media-clean}
